spring:
  application:
    name: greeting-server

server:
  port: 8081

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true


eureka.client.enabled: true