spring:
  application:
    name: greeting-client

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

services:
  greeting-server: greeting-server


spring.cloud.kubernetes.enabled: false
eureka.client.enabled: true